name: All tests pipeline

on:  
  workflow_dispatch:

jobs: 
  api:  
    name: Build and test API
    runs-on: ubuntu-latest
        
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v1 
      with:  
        dotnet-version: '8.0.x' 

    - name: Restore dependencies 
      run: dotnet restore 
      working-directory: ./api

    - name: Build 
      run: dotnet build --no-restore 
      working-directory: ./api

    - name: Run API tests
      run: dotnet test --no-build
      working-directory: ./api
      
    - name: Upload logs
      if: ${{always()}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Logs_Api
        path: EpamCom.TestFramework.Tests/Logs
        
  ui:  
    name: Build and test UI 
    runs-on: ubuntu-latest
    if: ${{always()}}
    strategy:
      matrix:
        browser: [Chrome, Edge, Firefox]
        
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v1 
      with:  
        dotnet-version: '8.0.x' 
 
    - name: Install Chrome
      if: ${{matrix.browser == 'Chrome'}}
      uses: browser-actions/setup-chrome@v1.7.2
      
    - name: Install Edge
      if: ${{matrix.browser == 'Edge'}}
      uses: browser-actions/setup-edge@v1.1.1

    - name: Install Firefox
      if: ${{matrix.browser == 'Firefox'}}
      uses: browser-actions/setup-firefox@v1.5.2

    - name: Restore dependencies 
      run: dotnet restore 
      working-directory: ./ui

    - name: Build 
      run: dotnet build --no-restore 
      working-directory: ./ui

    - name: Run UI tests
      id: test
      run: dotnet test --no-build -e BROWSER="${{matrix.browser}}"
      working-directory: ./ui
      
    - name: Upload logs
      if: ${{always()}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Logs_${{matrix.browser}}
        path: EpamCom.TestFramework.Tests/Logs
        
    - name: Upload failed tests screenshots
      if: ${{failure() && steps.test.outcome != 'success'}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: FailsScreenshots_${{matrix.browser}}
        path: EpamCom.TestFramework.Tests/FailsScreenshots
