name: UI tests pipeline manual run

on:  
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Browser type
        required: true
        options: 
          - Chrome
          - Firefox
          - Edge
jobs:  
  build:  
    name: Build and tests (${{inputs.browser}})
    runs-on: ubuntu-latest
        
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 

    - name: Setup .NET 
      uses: actions/setup-dotnet@v1 
      with:  
        dotnet-version: '8.0.x' 
 
    - name: Install Chrome
      if: ${{inputs.browser == 'Chrome'}}
      uses: browser-actions/setup-chrome@v1.7.2
      
    - name: Install Edge
      if: ${{inputs.browser == 'Edge'}}
      uses: browser-actions/setup-edge@v1.1.1

    - name: Install Firefox
      if: ${{inputs.browser == 'Firefox'}}
      uses: browser-actions/setup-firefox@v1.5.2

    - name: Restore dependencies 
      run: dotnet restore 
      working-directory: ./ui

    - name: Build 
      run: dotnet build --no-restore 
      working-directory: ./ui

    - name: Run tests
      id: test
      run: dotnet test --no-build -e BROWSER="${{inputs.browser}}"
      working-directory: ./ui
      
    - name: Upload logs
      if: ${{always()}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Logs_${{inputs.browser}}
        path: EpamCom.TestFramework.Tests/Logs
        
    - name: Upload failed tests screenshots
      if: ${{failure() && steps.test.outcome != 'success'}}
      uses: actions/upload-artifact@v4.6.0
      with:
        name: FailsScreenshots_${{inputs.browser}}
        path: EpamCom.TestFramework.Tests/FailsScreenshots
